services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5421:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: